### ISSUE TITLE
Call to /main/main.json fails behind load balance/nginx

### ISSUE THREAD

**Issue by frankhsu** [pingf/falsy#2]
I've put this service behind a load balancer and nginx, seems like the code calling /main/main.json is not CORS compliant?

Getting

`Could not read http://xxxx/main/main.json from server. Common errors include: URL is not https, server does not implement CORS correctly, or the url is mistyped. Check the developer console for more details.`

**Comment by pingf** [comment]
1. update falsy to latest version  `pip install -U falsy`
2. for example, use the gunicorn to start it like this `gunicorn -b 127.0.0.1:8001 serve:api  -w 1 --reload`
3. check the nginx conf, make sure it looks like this
```
server {
             listen 8090;
             server_name localhost:8001;
	     charset utf-8;

		location / {
                    proxy_pass http://127.0.0.1:8001;
                    proxy_set_header Host $host;
                    proxy_redirect off;
                    proxy_http_version 1.1;
                   proxy_set_header Upgrade $http_upgrade;
                   proxy_set_header Connection "upgrade";
		}
	}
```

now when you call your ip:8090/v1/ui  (modify it to your config), it will  redirect to 127.0.0.1:8001/v1/ui  correctly.

hoping it will solve your problem~

**Comment by pingf** [comment]
the other thing I should mention here is the cors config,  the default configuration only accepted the call from the binding address when you start your gunicorn.

to change it,
`f.swagger('test.yml', cors_origin='http://<youraddress>', theme='impress')`
or simply
`f.swagger('test.yml', cors_origin='*', theme='impress')`

still, make sure the falsy updated to latest version.

**Comment by frankhsu** [comment]
on chrome, i'm still seeing in the network call a request for /spec.json with a request URL as  `Request URL:http://0.0.0.0:8001/main/spec.json` but i should be seeing `Request URL:https://<myaddress>/main/spec.json`

**Comment by pingf** [comment]
can you tell me your command to start the gunicorn and the nginx config :) ?

**Comment by frankhsu** [comment]
Thanks for all the help so far!!!

CMD
```gunicorn -b 0.0.0.0:8001 serve:api --reload -w 3 --threads 3 --access-logfile /var/www/logs/access.log --error-logfile /var/www/logs/error.log --forwarded-allow-ips * --proxy-allow-from *```

nginx
```
upstream <mysite> {
  server 127.0.0.1:8001 fail_timeout=0;
}
server {
  listen 80;
  server_name <mysite>;

  client_max_body_size 20m;
  keepalive_timeout 15;

  location / {
    if ($http_x_forwarded_proto != "https") {
      rewrite ^(.*)$ https://$host$1 permanent;
    }

    proxy_set_header X-Request-Start "t=${msec}";
    proxy_set_header X-Real_IP $remote_addr;
    proxy_set_header X-Forwarded_For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_pass http://<mysite>;
  }
}```

my setup is ELB -> NGINX -> DOCKER -> FALSY

**Comment by frankhsu** [comment]
one thing to note, all the other endpoints work as expected (api paths, etc.).
it's just the UI path that gets this CORS/http(s) issue.

**Comment by frankhsu** [comment]
perhaps https://github.com/pingf/falsy/blob/master/falsy/swagger_proxy/middleware.py#L119
needs to be more flexible and not coded as `http`?

**Comment by pingf** [comment]
yeah, thx. it seems I forgot to change this part. I'm moving to a new apartment this weekend. I'll update it as soon as possible.

**Comment by pingf** [comment]
Hi,I've change it to 
```
'api_url': environ['wsgi.url_scheme']+'://' + environ['SERVER_NAME']+':'+environ['SERVER_PORT'] + '/' + self.swagger_file
```
hope it works now~
and tell me whether it works or not please~ :P

**Comment by pingf** [comment]
Just update my nginx config for using ssl, and solve the problem.
it's sth about cors, which forbids you making any http call via https page.
so, you need make your gunicorn run under ssl.
1. generate .crt and .key file or apply from the auth site. 
2. run gunicorn under https
```
gunicorn -b xxxx:xxx xxx:api -w 8 -k gevent  --certfile=/xxx/nginx.crt --keyfile=/xxx/nginx.key --reload
```
3. make nginx run under https.
```
server {
    listen 443;
    server_name xxx.xxx.xxx;

    location /xxx/ {
        proxy_pass https://xxxxx:xxx/v1/;
    }

       access_log            /var/log/nginx/auth_443.access.log;
    ssl_certificate           /xxx/nginx.crt;
    ssl_certificate_key       /xxx/nginx.key;

    ssl on;
    ssl_session_cache  builtin:1000  shared:SSL:10m;
    ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
    ssl_prefer_server_ciphers on;
}
```

replace 'xxx' with your config.
