### ISSUE TITLE
Errors running the example

### ISSUE THREAD

**Issue by Mancuerna** [pingf/falsy#3]
I'm trying to run the example provided in the README.md but I'm getting this error in two different machines (brand new virtualenv with just Falsy installed):

![](https://i.imgur.com/qw0TIXU.png)

Any idea of what could cause this error?

Thank you.

**Comment by pingf** [comment]
Hi, sorry for the late reply, I'm on vacation these days.
the indentation in the yml file(in the readme) is wrong, just updated it, should works now :grin:

**Comment by Mancuerna** [comment]
Thank you very much for checking this on vacation 💃
